{
 "title": "ISP Monitoring",
 "description": "Monitor your ISP's Ping and DNS response times. Collect useful data like packet loss, uptime metrics on upstream services.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Avg Ping Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "1.1.1.1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_average_response_ms{url=\"nu.nl\"}"
    }
   ]
  },
  {
   "title": "kpn.com",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_average_response_ms{url=\"steampowered.com\"}"
    }
   ]
  },
  {
   "title": "tweakers.net",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_average_response_ms{url=\"google.nl\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "google.nl",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_average_response_ms{url=\"google.nl\"}",
     "legendFormat": "$url"
    }
   ]
  },
  {
   "title": "Upstream Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Droplet",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms", "label": "Ping (ms)" }
   ],
   "targets": [
    {
     "expr": "ping_minimum_response_ms{url=\"google.nl\"}",
     "legendFormat": "min"
    },
    {
     "expr": "ping_average_response_ms{url=\"tweakers.net\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "ping_maximum_response_ms{url=\"kpn.com\"}",
     "legendFormat": "max"
    },
    {
     "expr": "ping_percent_packet_loss{url=\"1.1.1.1\"}",
     "legendFormat": "loss"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms", "label": "Ping (ms)" }
   ],
   "targets": [
    { "expr": "ping_average_response_ms{}", "legendFormat": "{{url}}" }
   ]
  },
  {
   "title": "Packet Loss %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent", "label": "Loss" }
   ],
   "targets": [
    { "expr": "ping_percent_packet_loss{}", "legendFormat": "{{url}}" }
   ]
  },
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "nu.nl",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg_over_time(ping_percent_packet_loss{url=\"nu.nl\"}[2m])"
    }
   ]
  },
  {
   "title": "steampowered.com\"",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg_over_time(ping_percent_packet_loss{url=\"steampowered.com\"}[2m])"
    }
   ]
  },
  {
   "title": "youtube.nl",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg_over_time(ping_percent_packet_loss{url=\"youtube.nl\"}[2m])"
    }
   ]
  },
  {
   "title": "google.nl",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg_over_time(ping_percent_packet_loss{url=\"google.nl\"}[2m])"
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "dns_query_query_time_ms", "legendFormat": "{{domain}}" }
   ]
  }
 ]
}