global:
  scrape_interval:     120s # By default, scrape targets every 15 seconds.
  evaluation_interval: 120s # By default, scrape targets every 15 seconds.

  external_labels:
      monitor: 'mikrotik-monitoring'

rule_files:

scrape_configs:
  - job_name: 'mikrotik'

    scrape_interval: 15s

    static_configs:
         - targets:
            - 'mktxp:49090'

  - job_name: 'blackbox'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [icmp_ttl5]  # use ICMP as the ping protocol
    static_configs:
      - targets:
        - 8.8.8.8       #GOOGLE DNS
        - 1.1.1.1       #CLOUDFLARE DNS
        - 195.121.1.34  #KPN DNS1
        - 195.121.1.66  #KPN DNS2
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackbox-http'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]  # use HTTP as the protocol
    static_configs:
      - targets:
        - https://github.com
        - https://nu.nl
        - https://kpn.com
        - https://google.nl
        - https://netflix.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.

  - job_name: "ispmonitor"
    scrape_interval: 15s
    static_configs:
      - targets: ["local_ip:9283"] # RPi telegraf Agent
