  
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: speedtest_db
    user: kpn
    password: kpn
    url: http://influxdb:8086
